02 python conditional and loop 변역 완료
fora22/TranslateGKO pull request #6
Opened 2020-06-17 06:21 UTC by fora22

오타
forece -> force

수정
pass문에 대한 영어 설명 중 `but`을 빼야 더 알맞음 문장 같다고 추측됨

2020-06-18 04:53 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +
영어 원문 전부 삭제할 것

2020-06-18 11:32 UTC, GKO95 requested changes
네 가지의 분류로 나누어서 첨삭.
1. **필수**: 반드시 변경
2. **권장**: 변경을 하기를 바람 (타당한 이유가 있으면 의문 제기)
3. **선택**: 선택적 변경사항 (강제성 없음)
4. **의문**: 첨삭자도 궁금해서 물어보는 것.

_지적 사항을 다 해결되었다고 더 이상 수정할 내용이 없다는 것은 절대 아님!_

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +
**필수**: 영어 원문 삭제

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +# **파이썬: 조건문과 반복문
**필수**: 볼드체 수정

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +# 두번째 print에 들여쓰기가 된 모습.
**권장**: "들여쓰기가 된 모습"을 "들여쓰기가 된 경우" 변경

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +# 두번째 print에 들여쓰기가 되지 않은 모습.
**권장**: "들여쓰기가 되지 않은 모습"을 "들여쓰기가 되지 않은 경우" 변경

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +조건부 `elif`문은 `if`와 `else`문의 조합으로 첫 번째 조건이 거짓이고, 첫 번째 조건과 다른 조건을 평가할 수 있는 두 번째(혹은 그 이상) 기회를 제공한다.
**권장**: "조건이 거짓이고,"를 "조건이 거짓일 경우,"로 변경

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +elif 조건:
**선택**: 위의 `if 조건1:`을 고려하여 `elif 조건2:`로 변경

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +이것은 다른 두 가지 조건부 집합의 조합인 반면에, `elif`는 하나의 조건부 집합을 보장한다는 점에서 `else`-`if` 조건부 문장과는 연결되지 않는다.
**필수**: 무슨 말인지 이해가 되지 않음.
> `else`-`if` 조건부 결합은 `elif` 조건부와 다른 존재임을 설명

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +*ternary*는 세 가지 인수를 사용하는 문장을 나타낸다. 3차 연산자는 가독성을 감소시키므로 과용해서는 안되지만 변수 할당에는 유용하다.
**권장**: Ternary 연산잔를 "조건 연산자"로 변경
> 출처: https://ko.wikipedia.org/wiki/%3F:

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +`while` 반복문은 조건이 유지되는 한 내부(일명 반복) 문장을 반복적으로 실행한다. 조건이 `False`임을 판단하면 반복이 종료된다.
**필수**: "(일명 반복)" 삭제

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +`else`문은 `while`문 뒤에 따라올 수 있으며, 반복 문장이 성공적으로 반복(조건 평균으로)되었을 때 실행된다.
**필수**: 재번역
> conditional mean에서 mean은 평균이 아닌 "수단"을 의미

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +# 끝난 루프: 반복 완료
**필수**: "루프 정상적 종료"으로 변경

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +# 끝난 루프: break문으로 강제 처리됨
**필수**: "루프 비정상 종료 (break 문 탈출)"으로 변경

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +`for` 반복문은 유효한 범위에 있는 한 내부(일명 반복) 문장을 반복적으로 실행한다. 범위의 모든 값이 반복되면 루프가 종료된다.
**필수**: "(일명 반복)" 삭제

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +3. string 객체: 문자열을 구성하는 문자를 반환한다.
**선택**: range, list, string을 "범위", "리스트", "문자열" 변경
> 출처: https://docs.python.org/ko/3/library/stdtypes.html?highlight=range#range

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +`else` 문장은 `for` 루프 문 다음에 나타날 수 있다. 루프 문장은 루프 문장이 성공적으로 반복을 마쳤을 때(범위가 부족하여) 실행된다.
**권장**: "(범위가 부족하여)" 삭제

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +# 끝난 루프: 반복 완료
**필수**: "루프 정상적 종료"으로 변경

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +# 끝난 루프: break문으로 강제 처리됨
**필수**: "루프 비정상 종료 (break 문 탈출)"으로 변경

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +예외는 오류 전용 조건문이다. 이 문장은 잘못된 코딩이나 입력으로 인해 실행 불가능한지 여부를 확인하고 프로그램을 즉시 중지한다. 스크립트 오류를 처리하는 데 사용할 수 있는 몇 가지 문이 있따.
**필수**: 오타 발견

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +`try`/`except` 문 쌍은 예외를 처리하고 예외 발생에 해당하는 특정 문을 호출하는 데 사용된다. 다음 쌍과 함께 사용할 수 있는 추가 문장이 있다.
**문의**: "`try`/`except` 문 쌍은"에서 "쌍은"이란 용어를 삭제 혹은 대체 단어 사용.

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +| `finally` | [선택사항: 어떤 예외가 발생했든, 오류가 없더라도 실행된 코드 블록이다.] |
**필수**: Description은 "설명" ("표현" X )
**권장**: `finally`에서 표현법 통일을 위해 "실행할 코드 블록이다."로 변경, 혹은 다른 방법으로 네 가지 표현법 통일 바람.

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +except:			# UNCONDITIONAL EXCEPTION LOCATES LAST.
**필수**: 주석 `# 전조건 예외처리는 마지막에 위치` 변경

2020-06-18 11:32 UTC, GKO95 commented on Python/02_PYTHON_CONDITIONAL_AND_LOOP.md
> +`raise`문은 수동으로 의도적으로 예외를 처리하는데 사용된다. 이 명령문은 오류가 발생하면 런타임도 즉시 중지하므로 더 이상 실행되지 않는다.
**권장**: 런타임을 영어로 "runtime" 혹은 한글로 "실행"으로 변경

2020-06-25 08:45 UTC, fora22 commented
모든 수정사항 수정 완료~

2020-06-25 11:30 UTC, GKO95 commented
가운데 첨삭 부분은 하나도 건들지 않았네. 수정 완료한 것은 Resolve Conversation 버튼 클릭해서 하나씩 체크하기.

2023-06-12 02:16 UTC, closed without merging